[package]
name = "arm-retour"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = "0.14.0"
libc = "0.2.147"
log = "0.4.20"
minidl = "0.1.5"
once_cell = "1.18.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
