[build]
target = "armv7-linux-androideabi"

# TODO: do not hardcode this?
[target.armv7-linux-androideabi]
linker = "/Users/brandon/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi23-clang"
